apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: letssee4-project
  namespace: argocd
spec:
  description: Project for letssee4
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - name: '*'
    namespace: '*'
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - '*'